<?php

declare(strict_types=1);

namespace Besdk\Target\Php\Tests;

use Besdk\Target\Php\Emitter;
use PHPUnit\Framework\TestCase;

final class EmitterTest extends TestCase
{
    /**
     * What the core sends in `TargetInput.brand`. Required rather than defaulted: a hardcoded fallback in
     * the target is exactly what carrying it over the protocol exists to prevent (SPEC.md §1.2).
     *
     * @var array<string,string>
     */
    private const BRAND = [
        'name' => 'besdk',
        'title' => 'besdk',
        'homepage' => 'https://example.invalid',
        'configFile' => 'besdk.yaml',
        'generatedNotice' => 'Code generated by besdk. DO NOT EDIT.',
        'attribution' => '_Generated by besdk._',
    ];

    /**
     * @param  array<string,mixed> $overrides
     * @return array<string,mixed>
     */
    private function ir(array $overrides = []): array
    {
        return array_merge([
            'irVersion' => '1.5.0',
            'service' => [
                'name' => ['tokens' => ['acme']],
                'displayName' => 'Acme',
                'version' => '1.0',
                'docs' => [],
                'servers' => [['url' => 'https://api.acme.com', 'default' => true, 'docs' => []]],
                'auth' => [['kind' => 'bearer', 'docs' => []]],
                'constantHeaders' => [],
            ],
            'types' => [],
            'resources' => [],
            'errors' => ['byStatus' => []],
            'pagination' => [],
        ], $overrides);
    }

    /**
     * @param  array<string,mixed> $ir
     * @param  array<string,mixed> $options
     * @return array<string,string>
     */
    private function emit(array $ir, array $options = []): array
    {
        $emitter = new Emitter($ir, array_merge(['packageName' => 'acme/sdk'], $options), self::BRAND);
        $out = [];
        foreach ($emitter->emit([]) as $file) {
            $out[$file['path']] = $file['contents'];
        }

        return $out;
    }

    /**
     * @param array<string,mixed> $fieldOverrides
     * @return array<string,mixed>
     */
    private function widgetType(array $fieldOverrides = []): array
    {
        return [
            'id' => 'Widget',
            'kind' => 'object',
            'name' => ['tokens' => ['widget']],
            'role' => 'read',
            'cyclic' => false,
            'docs' => [],
            'fields' => [
                array_merge([
                    'name' => ['tokens' => ['id']],
                    'wireName' => 'id',
                    'type' => ['kind' => 'primitive', 'type' => 'string'],
                    'required' => true,
                    'serverOwned' => true,
                    'readOnly' => false,
                    'writeOnly' => false,
                    'deprecated' => false,
                    'docs' => [],
                ], $fieldOverrides),
            ],
        ];
    }

    public function testEveryFileIsSyntacticallyValidPhp(): void
    {
        // The cheapest possible guard on the emitter, and the one that catches a broken string join before
        // it reaches a snapshot review.
        $files = $this->emit($this->ir(['types' => [$this->widgetType()]]));
        foreach ($files as $path => $contents) {
            if (!str_ends_with($path, '.php')) {
                continue;
            }
            $check = @token_get_all($contents, \TOKEN_PARSE);
            self::assertNotSame([], $check, $path . ' did not parse');
        }
    }

    public function testReadModelsAreFinalReadonlyWithPromotedProperties(): void
    {
        $files = $this->emit($this->ir(['types' => [$this->widgetType()]]));
        $widget = $files['src/Widget.php'] ?? '';
        self::assertStringContainsString('final readonly class Widget', $widget);
        // Promoted constructor properties, so the class body is the constructor and nothing else.
        self::assertStringContainsString('public string $id,', $widget);
    }

    public function testAnEnumIsNativeAndDecodedWithTryFrom(): void
    {
        $files = $this->emit($this->ir([
            'types' => [[
                'id' => 'Status',
                'kind' => 'enum',
                'name' => ['tokens' => ['status']],
                'docs' => [],
                'members' => [
                    ['name' => ['tokens' => ['active']], 'wireValue' => 'active', 'docs' => []],
                    ['name' => ['tokens' => ['archived']], 'wireValue' => 'archived', 'docs' => []],
                ],
            ]],
        ]));
        $source = $files['src/Status.php'] ?? '';
        // Native since 8.1. `tryFrom` is the open-enum behaviour §3.3.1 requires: a member the server adds
        // later returns null rather than throwing.
        self::assertStringContainsString('enum Status: string', $source);
        self::assertStringContainsString("case Active = 'active';", $source);
        self::assertStringContainsString('tryFrom', $source);
    }

    public function testARequiredFieldOfTheWrongTypeThrowsNamingTheField(): void
    {
        $widget = $this->emit($this->ir(['types' => [$this->widgetType()]]))['src/Widget.php'] ?? '';
        // Narrowed into a local before the constructor call, so PHPStan can prove the argument and the
        // failure names the field rather than surfacing as a TypeError from inside a constructor.
        self::assertStringContainsString('if (!is_string($id)) {', $widget);
        self::assertStringContainsString("throw self::decodeError('id', 'a string');", $widget);
    }

    public function testAnOptionalFieldOfTheWrongTypeBecomesNull(): void
    {
        $widget = $this->emit($this->ir([
            'types' => [$this->widgetType(['required' => false])],
        ]))['src/Widget.php'] ?? '';
        self::assertStringContainsString('$id = is_string($id) ? $id : null;', $widget);
    }

    public function testTheHttpVerbComesFromTheIrRatherThanADefault(): void
    {
        // The bug this pins: the emitter read `http.method`, which the IR does not have — every method was
        // emitted as a GET, including creates. A silent wrong-verb bug that every gate passes.
        $files = $this->emit($this->ir([
            'types' => [$this->widgetType()],
            'resources' => [[
                'id' => 'widgets',
                'name' => ['tokens' => ['widgets']],
                'docs' => [],
                'subresources' => [],
                'methods' => [[
                    'name' => ['tokens' => ['create']],
                    'operationId' => 'createWidget',
                    'docs' => [],
                    'deprecated' => false,
                    'http' => ['verb' => 'post', 'path' => '/widgets', 'params' => []],
                    'body' => [
                        'type' => ['kind' => 'named', 'id' => 'Widget'],
                        'contentType' => 'application/json',
                        'required' => true,
                    ],
                    'response' => ['kind' => 'json', 'statusCode' => 201, 'type' => ['kind' => 'named', 'id' => 'Widget']],
                ]],
            ]],
        ]));
        $resource = $files['src/WidgetsResource.php'] ?? '';
        self::assertStringContainsString("requestJson('POST'", $resource);
        self::assertStringNotContainsString("requestJson('GET'", $resource);
    }

    public function testQueryAndPathParametersAreReadFromOneParamsList(): void
    {
        // `http.params` is one list discriminated by `location`, not `pathParams`/`queryParams`. Reading the
        // latter produced methods with no parameters at all — silently.
        $files = $this->emit($this->ir([
            'resources' => [[
                'id' => 'widgets',
                'name' => ['tokens' => ['widgets']],
                'docs' => [],
                'subresources' => [],
                'methods' => [[
                    'name' => ['tokens' => ['get']],
                    'operationId' => 'getWidget',
                    'docs' => [],
                    'deprecated' => false,
                    'http' => [
                        'verb' => 'get',
                        'path' => '/widgets/{id}',
                        'params' => [
                            [
                                'name' => ['tokens' => ['id']],
                                'wireName' => 'id',
                                'location' => 'path',
                                'type' => ['kind' => 'primitive', 'type' => 'string'],
                                'required' => true,
                                'deprecated' => false,
                                'docs' => [],
                            ],
                            [
                                'name' => ['tokens' => ['expand']],
                                'wireName' => 'expand',
                                'location' => 'query',
                                'type' => ['kind' => 'primitive', 'type' => 'string'],
                                'required' => false,
                                'deprecated' => false,
                                'docs' => [],
                            ],
                        ],
                    ],
                    'response' => ['kind' => 'empty', 'statusCode' => 204],
                ]],
            ]],
        ]));
        $resource = $files['src/WidgetsResource.php'] ?? '';
        self::assertStringContainsString('string $id', $resource);
        self::assertStringContainsString('?string $expand = null', $resource);
        // The path parameter is substituted and percent-encoded, so an id containing a slash cannot escape
        // its segment and reach a different endpoint.
        self::assertStringContainsString("Query::path('/widgets/{id}', ['id' => \$id])", $resource);
    }

    public function testNoSchemasFileWhenThereIsNothingToValidate(): void
    {
        // A spec whose responses are all untyped ships no table rather than an empty one.
        self::assertArrayNotHasKey('src/Schemas.php', $this->emit($this->ir()));
    }

    public function testTheComposerManifestUsesTheConfiguredPackageAndNamespace(): void
    {
        $files = $this->emit($this->ir(), ['packageName' => 'widgetco/sdk']);
        $manifest = json_decode($files['composer.json'] ?? '{}', true);
        self::assertIsArray($manifest);
        self::assertSame('widgetco/sdk', $manifest['name']);
        // PSR-4 from the package name, which is the mapping every PHP consumer expects.
        $autoload = $manifest['autoload'] ?? null;
        self::assertIsArray($autoload);
        $psr4 = $autoload['psr-4'] ?? null;
        self::assertIsArray($psr4);
        self::assertArrayHasKey('Widgetco\\Sdk\\', $psr4);
    }

    public function testNoFileNamesTheGeneratorOutsideTheSuppliedBrand(): void
    {
        // The brand is carried over the protocol precisely so a target cannot hardcode it. Generated files
        // are files consumers commit, so a rename must not break them.
        $brand = array_merge(self::BRAND, ['generatedNotice' => 'MADE BY XX. DO NOT EDIT.', 'name' => 'xx', 'attribution' => '_By xx._']);
        $emitter = new Emitter($this->ir(['types' => [$this->widgetType()]]), ['packageName' => 'acme/sdk'], $brand);
        foreach ($emitter->emit([]) as $file) {
            self::assertStringNotContainsStringIgnoringCase('besdk', $file['contents'], $file['path']);
        }
    }

    public function testAnOptionalNullableFieldIsNotDoublyNullable(): void
    {
        // `??string` is a syntax error, and it only appeared on a spec with a field that is both optional
        // and explicitly nullable — the guard checked for the substring `null`, which `?string` does not
        // contain. Caught by `php -l` on the kitchen-sink spec, not by any smaller fixture.
        $widget = $this->emit($this->ir([
            'types' => [$this->widgetType([
                'required' => false,
                'type' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']],
            ])],
        ]))['src/Widget.php'] ?? '';
        self::assertStringContainsString('public ?string $id = null,', $widget);
        // Scoped to a type position: `??` on its own is the null-coalescing operator, which the decoder
        // uses on every field.
        self::assertStringNotContainsString('??string', $widget);
        self::assertStringNotContainsString('??int', $widget);
    }
}
