/**
 * `graft init` — scaffold a `graft.yaml` from what analysis found.
 *
 * The design rule, from SPEC.md §6: **write inferred values explicitly.** A config that omits
 * everything graft could guess would leave the user unable to see, review, or override those
 * guesses — the overlay would be magic. So this writes the inferences down, with the
 * diagnostic code that produced each one, and marks the judgments only the API owner can make.
 *
 * This emits YAML as text rather than through a builder because the *comments* are most of the
 * value here, and they are what makes the file reviewable in a PR. (The "ASTs, never
 * templates" rule in AGENTS.md governs generated SDK *code*, where import management and type
 * deduplication are the reason templates fail. It does not govern an annotated config file.)
 */

import { getArray, getObject, getString } from './json.js';
import type { Inspection } from './inspect.js';
import {
  findAllOptionalObjects,
  findConstantHeaders,
  findPaginationCandidates,
  findReadWriteConflation,
  suggestModelName,
  surveyErrorResponses,
} from './analyze.js';
import { BRAND } from '@graft/protocol';

/** Field names conventionally assigned by the server rather than supplied by the client. */
const SERVER_OWNED_PATTERNS = [
  /^_?id$/i,
  /^created(_?at|_?on)?$/i,
  /^updated(_?at|_?on)?$/i,
  /^modified(_?at|_?on)?$/i,
  /^deleted(_?at|_?on)?$/i,
  /^_(created|updated|modified)$/i,
  /^(created|updated)By$/i,
  /^(uuid|slug|revision|version|etag)$/i,
];

function looksServerOwned(field: string): boolean {
  return SERVER_OWNED_PATTERNS.some((pattern) => pattern.test(field));
}

/**
 * Words YAML 1.1 readers coerce to booleans or null. Emitting them plain would turn the
 * string `"no"` into `false` on the way back in.
 */
const YAML_KEYWORDS = new Set([
  'true', 'false', 'yes', 'no', 'on', 'off', 'null', 'nil', '~', 'y', 'n',
]);

/**
 * Quote a YAML scalar only when it needs it, so the file stays readable.
 *
 * Conservative by construction: emit plain only for values that are unambiguously safe, and
 * double-quote everything else. The failure this guards against is real — an earlier version
 * emitted `packageName: @scope/sdk` plain, and `@` is a *reserved* indicator that cannot begin
 * a plain scalar, so `graft init` produced a config `graft` itself refused to parse.
 */
export function scalar(value: string): string {
  if (value === '') return "''";

  // Must begin with a letter or underscore: rules out every YAML indicator character
  // (`@`, `%`, `&`, `*`, `!`, `|`, `>`, `#`, `-`, `?`, `:`, `,`, `[`, `]`, `{`, `}`, quotes)
  // and any leading digit that could read as a number.
  if (!/^[A-Za-z_]/.test(value)) return JSON.stringify(value);

  // `: ` opens a mapping and ` #` opens a comment, in any position.
  if (value.includes(': ') || value.includes(' #')) return JSON.stringify(value);
  if (value.endsWith(':')) return JSON.stringify(value);

  // Leading/trailing whitespace does not survive a plain scalar.
  if (value !== value.trim()) return JSON.stringify(value);

  if (YAML_KEYWORDS.has(value.toLowerCase())) return JSON.stringify(value);

  // Remaining characters must be from a set that carries no structural meaning.
  if (!/^[A-Za-z0-9_.\-/ ]*$/.test(value.slice(1))) return JSON.stringify(value);

  return value;
}

/** Scalar types the `errors.*.schema` shorthand accepts. Anything else narrows to `unknown`. */
const SHORTHAND_SCALARS = new Set(['string', 'integer', 'number', 'boolean']);

function shorthandTypeFor(definition: unknown): string {
  const declared = getString(definition, 'type');
  return declared !== undefined && SHORTHAND_SCALARS.has(declared) ? declared : 'unknown';
}

function derivePackageName(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return `@${slug || 'api'}/sdk`;
}

export interface InitOptions {
  /** Spec path to record in the config, as the user typed it. */
  readonly specPath: string;
  /** Targets to scaffold. */
  readonly targets?: readonly string[];
}

export function renderInitConfig(inspection: Inspection, options: InitOptions): string {
  const { resolved, index, spec } = inspection;
  const title = getString(getObject(spec.document, 'info'), 'title') ?? 'API';
  const targets = options.targets ?? ['typescript'];

  const out: string[] = [];
  const push = (line = ''): void => void out.push(line);

  push(`# ${BRAND.title} configuration for ${title}`);
  push('#');
  push(`# Generated by \`${BRAND.name} init\`. Inferred values are written out explicitly rather than`);
  push(`# left implicit, so you can see and override every judgment ${BRAND.title} made.`);
  push('#');
  push(`# Lines marked REVIEW encode knowledge only the API owner has. ${BRAND.title} cannot infer them`);
  push('# from the spec, and leaving them wrong produces an SDK that compiles but misleads.');
  push();
  push(`spec: ${scalar(options.specPath)}`);
  push(`name: ${scalar(title)}`);
  push();

  // --- targets -------------------------------------------------------------
  push('targets:');
  for (const target of targets) {
    push(`  ${target}:`);
    push(`    out: ${scalar(`sdks/${target}`)}`);
    push(`    packageName: ${scalar(derivePackageName(title))}`);
  }
  push();

  // --- errors (E001) -------------------------------------------------------
  const errors = surveyErrorResponses(index);
  if (errors.untyped > 0) {
    push(`# [E001] ${errors.untyped} of ${errors.total} error responses declare no schema.`);
    const declared = [...errors.declaredShapes.values()].sort((a, b) => b.count - a.count)[0];
    if (declared !== undefined) {
      push(
        `# The spec does declare a shape on ${declared.count} response${
          declared.count === 1 ? '' : 's'
        }; reusing it as the default.`,
      );
    } else {
      push('# REVIEW: no error shape appears anywhere in the spec. This is a guess.');
    }
    push('errors:');
    push('  default:');
    push('    schema:');
    const properties = declared ? getObject(declared.sample, 'properties') : undefined;
    const requiredList = declared ? (getArray(declared.sample, 'required') ?? []) : [];
    if (properties !== undefined) {
      for (const [field, def] of Object.entries(properties)) {
        const isRequired = requiredList.includes(field);
        // The shorthand only expresses scalars, so anything else becomes `unknown` — honest, and
        // still valid config. Emitting the spec's own `array`/`object` produced a config that
        // graft itself rejected: GitHub's error body has an `errors` array.
        push(`      ${field}: ${shorthandTypeFor(def)}${isRequired ? '' : '?'}`);
      }
    } else {
      push('      error: string');
    }
    push();
  }

  // --- pagination (P001/P002) ---------------------------------------------
  const candidates = findPaginationCandidates(index, resolved.resolve);
  // Must match the diagnostic's notion of a collection, or `check` reports pagination that
  // `init` then declines to write — the two would disagree about the same spec.
  const isCollection = (c: (typeof candidates)[number]): boolean =>
    c.evidence === 'array' || c.evidence === 'envelope';
  const confirmed = candidates.filter(isCollection);
  const withheld = candidates.filter((c) => !isCollection(c));
  if (candidates.length > 0) {
    if (confirmed.length > 0) {
      const first = confirmed[0]!;
      const style =
        first.cursorParam !== undefined
          ? 'cursor'
          : first.pageParam !== undefined
            ? 'page'
            : 'offset';
      const total = confirmed.find((c) => c.proseTotalHeader !== undefined)?.proseTotalHeader;
      push(
        `# [P001] ${confirmed.length} operation${
          confirmed.length === 1 ? '' : 's'
        } return a collection with paging parameters.`,
      );
      push('pagination:');
      push('  default:');
      push(`    style: ${style}`);
      if (first.limitParam) push(`    limit: ${first.limitParam}`);
      if (first.offsetParam) push(`    offset: ${first.offsetParam}`);
      if (first.pageParam) push(`    page: ${first.pageParam}`);
      if (first.cursorParam) push(`    cursor: ${first.cursorParam}`);
      // An envelope needs its paths written out, or the runtime cannot find the items.
      const envelope = confirmed.find((c) => c.envelope !== undefined)?.envelope;
      if (envelope !== undefined) {
        push(`    items: ${scalar(`body:${envelope.itemsPath.join('.')}`)}`);
        if (envelope.cursorPath !== undefined) {
          push(`    cursorFrom: ${scalar(`body:${envelope.cursorPath.join('.')}`)}`);
        }
        if (envelope.totalPath !== undefined) {
          push(`    total: ${scalar(`body:${envelope.totalPath.join('.')}`)}`);
        }
      }
      if (total !== undefined) {
        push(`    total: ${scalar(`header:${total}`)}`);
        push(`    # REVIEW: ${total} is named only in prose, never declared under`);
        push('    # responses.headers. Confirm the header name is exact.');
      }
    } else {
      push('# [P002] No operation could be confirmed as a paginated collection.');
      push('pagination:');
    }

    if (withheld.length > 0) {
      push();
      push(
        `  # [P002] These accept paging parameters but do not return a collection, so ${BRAND.title}`,
      );
      push('  # does not paginate them. Change `none` to `default` for any that really do page.');
      push('  operations:');
      for (const candidate of withheld) {
        const key = candidate.operation.operationId ?? candidate.operation.path;
        const why =
          candidate.evidence === 'unknown' ? 'no response schema' : 'returns a single object';
        push(`    ${scalar(key)}: none   # ${why}`);
      }
    }
    push();
  }

  // --- models (M001/M002) --------------------------------------------------
  const conflated = findReadWriteConflation(index);
  const allOptional = new Map(findAllOptionalObjects(resolved).map((s) => [s.name, s]));
  if (conflated.length > 0 || allOptional.size > 0) {
    push('# [M001] Schemas used as both request and response bodies are split, so write');
    push('#        methods stop accepting server-owned fields.');
    push('# [M002] Schemas with no `required` fields make every property optional downstream.');
    push('models:');

    const names = new Set<string>([...conflated.map((c) => c.name), ...allOptional.keys()]);
    for (const name of [...names].sort()) {
      const schema = resolved.schemas.get(name);
      const properties = schema ? getObject(schema, 'properties') : undefined;
      const fields = properties ? Object.keys(properties) : [];
      const serverOwned = fields.filter(looksServerOwned);
      const isConflated = conflated.some((c) => c.name === name);
      const suggested = suggestModelName(name);

      push(`  ${name}:`);
      if (suggested !== name) push(`    rename: ${scalar(suggested)}`);
      if (isConflated) {
        push(
          `    split: { read: ${scalar(suggested)}, create: ${scalar(
            `${suggested}Create`,
          )}, update: ${scalar(`${suggested}Update`)} }`,
        );
      }
      if (serverOwned.length > 0) {
        push(`    serverOwned: [${serverOwned.join(', ')}]`);
      } else if (isConflated) {
        push('    # REVIEW: no conventionally-named server-owned fields found. List the fields');
        push('    #         the server assigns, or write methods will accept all of them.');
        push('    serverOwned: []');
      }
      if (allOptional.has(name)) {
        const hint = serverOwned.length > 0 ? serverOwned[0]! : (fields[0] ?? 'id');
        push(`    # REVIEW: ${fields.length} fields, none required in the spec.`);
        push(`    required: [${hint}]`);
      }
    }
    push();
  }

  // --- normalize -----------------------------------------------------------
  push(`# Normalizer rules. These are ${BRAND.title} defaults, written out so they are visible.`);
  push('normalize:');
  push('  phpEmptyMap: true       # [T001] collapse `object | array maxItems:0` to a map');
  push('  scalarUnion: widen      # [T002] `string | integer` stays a union rather than coercing');
  push('  constHeaderHoist: true  # [H001] see headers.constant below');
  push();

  // --- headers (H001) ------------------------------------------------------
  const constantHeaders = findConstantHeaders(index);
  if (constantHeaders.length > 0) {
    push(
      `# [H001] Constant on ${constantHeaders[0]!.operationCount}/${
        index.operations.length
      } operations, so hoisted out of every method signature.`,
    );
    push('headers:');
    push('  constant:');
    for (const header of constantHeaders) {
      push(`    ${header.name}: ${scalar(header.value)}`);
    }
    push();
  }

  // --- resources -----------------------------------------------------------
  const groups = [
    ...new Set(index.operations.map((op) => op.groupName).filter((g): g is string => g !== undefined)),
  ].sort();
  if (groups.length > 0) {
    push(`# [S002] ${groups.length} resource groups read from x-fern-sdk-group-name.`);
    push('# Uncomment a line to rename that resource in the generated client.');
    push('# resources:');
    for (const group of groups) {
      push(`#   ${group}: ${group}`);
    }
  }

  return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}
