package emit

import (
	"encoding/json"
	"sort"
	"strings"
	"testing"
)

// testBrand is what the core sends in TargetInput.brand. Required rather than defaulted: a
// hardcoded fallback in the target is what carrying it over the protocol exists to prevent.
var testBrand = Brand{
	Name:            "graft",
	Title:           "graft",
	Homepage:        "https://example.invalid",
	ConfigFile:      "graft.yaml",
	GeneratedNotice: "Code generated by graft. DO NOT EDIT.",
	Attribution:     "_Generated by graft._",
}

// Every test here pins a defect found by reading generated output or by building it. A generator's
// bugs are almost never "it crashed"; they are "it emitted something plausible and wrong".

func TestExportedHonoursInitialisms(t *testing.T) {
	// This is why the IR stores lowercase tokens: pascal() gives `UserId`, which is wrong in Go and
	// right in TypeScript. No pre-cased name could serve both.
	cases := map[string]string{
		"user id":      "UserID",
		"api key":      "APIKey",
		"display name": "DisplayName",
		"html url":     "HTMLURL",
		"uuid":         "UUID",
		"org id":       "OrgID",
	}
	for input, want := range cases {
		got := Exported(Name{Tokens: strings.Fields(input)})
		if got != want {
			t.Errorf("Exported(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestUnexportedKeepsTheFirstTokenLower(t *testing.T) {
	// `apiKey`, never `aPIKey`.
	if got := Unexported(Name{Tokens: []string{"api", "key"}}); got != "apiKey" {
		t.Errorf("Unexported = %q, want apiKey", got)
	}
}

func TestLocalNamesAvoidKeywords(t *testing.T) {
	// `type` is a syntax error as an identifier; `len` shadows a builtin generated bodies call.
	if got := LocalName(Name{Tokens: []string{"type"}}); got != "type_" {
		t.Errorf("LocalName(type) = %q", got)
	}
	if got := LocalName(Name{Tokens: []string{"len"}}); got != "len_" {
		t.Errorf("LocalName(len) = %q", got)
	}
}

func TestFieldNamesKeepTheirNaturalForm(t *testing.T) {
	// A struct field is only ever reached through a selector, so `w.Type` cannot collide with the
	// keyword. Suffixing it would mark almost every model as machine-made.
	if got := FieldName(Name{Tokens: []string{"type"}}); got != "Type" {
		t.Errorf("FieldName(type) = %q, want Type", got)
	}
}

func TestUniqueFieldDisambiguates(t *testing.T) {
	// `user_id` and `userId` both render to UserID, and a duplicate struct field does not compile.
	taken := map[string]bool{}
	first := UniqueField(Name{Tokens: []string{"user", "id"}}, taken)
	second := UniqueField(Name{Tokens: []string{"user", "id"}}, taken)
	if first != "UserID" || second != "UserID2" {
		t.Errorf("got %q then %q", first, second)
	}
}

func TestFileNameIsSnakeCase(t *testing.T) {
	cases := map[string]string{
		"Api20100401Address": "api20100401_address",
		"orgs.invoices":      "orgs_invoices",
		"HTTPServer":         "http_server",
		"already_snake":      "already_snake",
	}
	for input, want := range cases {
		if got := FileName(input); got != want {
			t.Errorf("FileName(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestLeadingDigitGetsAPrefix(t *testing.T) {
	if got := Exported(Name{Tokens: []string{"2010", "api"}}); !strings.HasPrefix(got, "N") {
		t.Errorf("Exported = %q, want a valid identifier", got)
	}
}

// --- builder ---------------------------------------------------------------

func TestDocCommentUsesNameColonForm(t *testing.T) {
	// A generator cannot conjugate a summary into English — "ListMembers list members" is not a
	// sentence. `Name: Summary` is the form Google's generated Go clients use.
	got := DocComment("", "ListMembers", Docs{Summary: "List members of an organization"})
	if !strings.HasPrefix(got, "// ListMembers: List members") {
		t.Errorf("DocComment = %q", got)
	}
}

func TestDocCommentLeavesAuthoredSentencesAlone(t *testing.T) {
	got := DocComment("", "Widget", Docs{Summary: "Widget is a thing you can buy."})
	if !strings.HasPrefix(got, "// Widget is a thing") {
		t.Errorf("DocComment rewrote an already-correct sentence: %q", got)
	}
}

func TestDocCommentWrapsProse(t *testing.T) {
	// gofmt does not reflow comments, so wrapping has to happen here.
	long := strings.Repeat("word ", 80)
	for _, line := range strings.Split(DocComment("\t", "X", Docs{Summary: long}), "\n") {
		if len(line) > 100 {
			t.Fatalf("line of %d chars: %q", len(line), line)
		}
	}
}

func TestDocCommentPreservesIndentedCode(t *testing.T) {
	// Rewrapping a code sample is how a generator turns a working example into a broken one.
	code := "\tit := client.Widgets.List(ctx, nil)"
	// Asserted through a rendered file, because gofmt is what normalises `// \t` to `//\t` — and the
	// point of the test is that the *content* survives unreflowed, not what the raw prefix looks like
	// before formatting.
	file := NewFile("demo")
	file.Add(DocComment("", "X", Docs{}, "Example:\n\n"+code) + "type X struct{}")
	rendered, err := file.Render()
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(rendered, "//\tit := client.Widgets.List(ctx, nil)") {
		t.Errorf("code block was reflowed:\n%s", rendered)
	}
}

func TestDocCommentStripsControlCharacters(t *testing.T) {
	got := DocComment("", "X", Docs{Summary: "before\x00\x07after"})
	if strings.ContainsAny(got, "\x00\x07") {
		t.Errorf("control characters survived: %q", got)
	}
}

func TestFileRenderIsGofmtted(t *testing.T) {
	file := NewFile("demo")
	file.Import("context")
	// Deliberately misformatted input: go/format is what decides layout, not this string.
	file.Add("type   Widget    struct {\nID   string\n}")
	got, err := file.Render()
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(got, "type Widget struct {") {
		t.Errorf("not gofmt-formatted:\n%s", got)
	}
}

func TestFileRenderReportsInvalidGoWithTheText(t *testing.T) {
	// When generation produces invalid Go, the *text* is what a maintainer needs; returning only an
	// error would hide the evidence.
	file := NewFile("demo")
	file.Add("func broken( {")
	text, err := file.Render()
	if err == nil {
		t.Fatal("expected an error")
	}
	if !strings.Contains(text, "func broken") {
		t.Error("the unformatted text was not returned alongside the error")
	}
}

func TestImportsAreGroupedStdlibFirst(t *testing.T) {
	file := NewFile("demo")
	file.Import("github.com/acme/x/internal/core")
	file.Import("context")
	got, err := file.Render()
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if strings.Index(got, `"context"`) > strings.Index(got, "internal/core") {
		t.Errorf("imports not grouped stdlib-first:\n%s", got)
	}
}

// --- emission --------------------------------------------------------------

// hasField reports whether source declares a struct field of the given name and type, ignoring the
// column alignment gofmt applies.
func hasField(source, name, goType string) bool {
	for _, line := range strings.Split(source, "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == name && fields[1] == goType {
			return true
		}
	}
	return false
}

func testIR(t *testing.T, body string) *IR {
	t.Helper()
	var ir IR
	if err := json.Unmarshal([]byte(body), &ir); err != nil {
		t.Fatalf("decoding test IR: %v", err)
	}
	return &ir
}

const minimalIR = `{
  "irVersion": "1.2.0",
  "service": {
    "name": {"tokens":["acme"]}, "displayName": "Acme", "version": "1.0", "docs": {},
    "servers": [{"url":"https://api.acme.com","default":true,"docs":{}}],
    "auth": [{"kind":"bearer","docs":{}}], "constantHeaders": {}
  },
  "types": [], "resources": [], "errors": {"byStatus": []}, "pagination": []
}`

func emitFiles(t *testing.T, ir *IR, opts string) map[string]string {
	t.Helper()
	e := New(ir, json.RawMessage(opts), testBrand)
	files, err := e.Emit(map[string]string{})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	out := map[string]string{}
	for _, f := range files {
		out[f.Path] = f.Contents
	}
	return out
}

func TestSelfReferentialStructBecomesAPointer(t *testing.T) {
	// Go embeds a struct by value, so `type A struct { A A }` is infinitely sized and does not
	// compile. Stripe has one. The IR's `cyclic` flag says the type participates in a cycle but not
	// which *field* closes it, so the edge is computed in the target.
	ir := testIR(t, `{
      "irVersion":"1.2.0",
      "service":{"name":{"tokens":["acme"]},"version":"1","docs":{},"servers":[],"auth":[],"constantHeaders":{}},
      "types":[{"kind":"object","id":"Node","name":{"tokens":["node"]},"docs":{},"role":"read","cyclic":true,
        "fields":[
          {"name":{"tokens":["id"]},"wireName":"id","type":{"kind":"primitive","type":"string"},
           "required":true,"serverOwned":false,"readOnly":false,"writeOnly":false,"deprecated":false,"docs":{}},
          {"name":{"tokens":["parent"]},"wireName":"parent","type":{"kind":"named","id":"Node"},
           "required":true,"serverOwned":false,"readOnly":false,"writeOnly":false,"deprecated":false,"docs":{}}
        ]}],
      "resources":[],"errors":{"byStatus":[]},"pagination":[]}`)
	models := emitFiles(t, ir, `{}`)["models.go"]
	// Whitespace-insensitive: gofmt aligns struct fields into columns, so an exact-spacing assertion
	// would test the formatter rather than the generator.
	if !hasField(models, "Parent", "*Node") {
		t.Errorf("a self-referential field must be a pointer:\n%s", models)
	}
	// And a scalar in the same struct must stay a value.
	if !hasField(models, "ID", "string") {
		t.Errorf("a required scalar was pointer-ised unnecessarily:\n%s", models)
	}
}

func TestEnumConstantsDoNotCollideWithTypes(t *testing.T) {
	// Go puts types and constants in one namespace. GitHub declares a struct `EventComment` and an
	// `Event` enum with a `COMMENT` member, and the second redeclared the first.
	ir := testIR(t, `{
      "irVersion":"1.2.0",
      "service":{"name":{"tokens":["acme"]},"version":"1","docs":{},"servers":[],"auth":[],"constantHeaders":{}},
      "types":[
        {"kind":"object","id":"EventComment","name":{"tokens":["event","comment"]},"docs":{},"role":"read","cyclic":false,"fields":[]},
        {"kind":"enum","id":"Event","name":{"tokens":["event"]},"docs":{},"open":true,
         "members":[{"name":{"tokens":["comment"]},"wireValue":"\"COMMENT\"","docs":{}}]}
      ],
      "resources":[],"errors":{"byStatus":[]},"pagination":[]}`)
	models := emitFiles(t, ir, `{}`)["models.go"]
	if strings.Count(models, "EventComment ") > 1 && strings.Contains(models, "EventComment Event") {
		// The constant must have been renamed, not redeclared.
		t.Errorf("enum constant collided with a type:\n%s", models)
	}
	if !strings.Contains(models, "type EventComment struct") {
		t.Errorf("the struct lost its name:\n%s", models)
	}
}

func TestNoModulePathWarns(t *testing.T) {
	// A wrong module path breaks `go get` for every consumer, so it cannot be silent.
	ir := testIR(t, minimalIR)
	e := New(ir, json.RawMessage(`{}`), testBrand)
	if len(e.Warnings()) == 0 {
		t.Error("expected a warning when modulePath is unset")
	}
	if !strings.Contains(e.Warnings()[0].Message, "modulePath") {
		t.Errorf("warning = %q", e.Warnings()[0].Message)
	}
}

func TestModulePathIsUsedForTheCoreImport(t *testing.T) {
	ir := testIR(t, minimalIR)
	files := emitFiles(t, ir, `{"modulePath":"github.com/acme/acme-go","packageName":"acme"}`)
	if !strings.Contains(files["client.go"], `"github.com/acme/acme-go/internal/core"`) {
		t.Errorf("client.go does not import the vendored runtime by module path:\n%s", files["client.go"])
	}
	if !strings.Contains(files["go.mod"], "module github.com/acme/acme-go") {
		t.Errorf("go.mod = %q", files["go.mod"])
	}
}

func TestClientNameDropsNoSuffix(t *testing.T) {
	// `acme.New()` already says what it constructs.
	ir := testIR(t, minimalIR)
	files := emitFiles(t, ir, `{"modulePath":"m","packageName":"acme"}`)
	if !strings.Contains(files["client.go"], "type Acme struct") {
		t.Errorf("client type is not Acme:\n%s", files["client.go"])
	}
}

func TestSanityCatchesAMisnamedField(t *testing.T) {
	// The check that exists because no gate over the *output* can catch a target reading the wrong
	// IR field: the output is well-formed, it just does nothing.
	ir := testIR(t, minimalIR)
	loose := map[string]any{
		"resources": []any{map[string]any{
			"methods": []any{map[string]any{"body": map[string]any{}, "http": map[string]any{"params": []any{}}}},
		}},
	}
	problems := Sanity(ir, loose)
	if len(problems) == 0 {
		t.Error("Sanity did not notice that resources failed to decode")
	}
}

func TestSanityPassesOnAConsistentIR(t *testing.T) {
	ir := testIR(t, minimalIR)
	if problems := Sanity(ir, map[string]any{}); len(problems) != 0 {
		t.Errorf("Sanity reported problems on an empty-but-consistent IR: %v", problems)
	}
}

// TestConfiguredIdempotencyHeaderReachesTheClient guards the threading, not the behaviour.
//
// The runtime already honoured a custom header; the target simply never passed one on, so
// `idempotencyHeader` in graft.yaml was accepted, validated, and silently discarded. That failure
// mode leaves every gate green — the SDK compiles, vets, and formats — which is why it needs a test
// naming the config key rather than a review.
func TestConfiguredIdempotencyHeaderReachesTheClient(t *testing.T) {
	files := emitFiles(t, testIR(t, minimalIR), `{"packageName":"acme","idempotencyHeader":"X-Idempotency-Key"}`)
	client := files["client.go"]
	if !strings.Contains(client, `IdempotencyHeader: "X-Idempotency-Key"`) {
		t.Fatalf("configured header missing from the client constructor:\n%s", client)
	}

	// Absent means the runtime default, not an empty string overriding it.
	plain := emitFiles(t, testIR(t, minimalIR), `{"packageName":"acme"}`)
	if strings.Contains(plain["client.go"], "IdempotencyHeader") {
		t.Fatalf("unconfigured client should not set IdempotencyHeader at all:\n%s", plain["client.go"])
	}
}

const templatedServerIR = `{
  "irVersion": "1.5.0",
  "service": {
    "name": {"tokens":["acme"]}, "displayName": "Acme", "version": "1.0", "docs": {},
    "servers": [{
      "url": "https://us-east-1.api.example.com/v2",
      "urlTemplate": "https://{region}.api.example.com/{version}",
      "variables": [
        {"wireName":"region","name":{"tokens":["region"]},"default":"us-east-1","enum":["us-east-1","eu-west-1"],"description":"Data residency."},
        {"wireName":"version","name":{"tokens":["version"]},"default":"v2"}
      ],
      "default": true, "docs": {}
    }],
    "auth": [], "constantHeaders": {}
  },
  "types": [], "resources": [], "errors": {"byStatus": []}, "pagination": []
}`

// TestTemplatedServerBecomesTypedOptions checks the Go answer to a union: a named string type with
// constants, which is what a caller can discover in an editor.
//
// The base URL is left as a template for the runtime to resolve, because Go applies functional options
// *after* the options struct is built — a constructor substituting inline would assemble the URL before
// WithRegion ever ran.
func TestTemplatedServerBecomesTypedOptions(t *testing.T) {
	client := emitFiles(t, testIR(t, templatedServerIR), `{"packageName":"acme"}`)["client.go"]

	for _, want := range []string{
		"type Region string",
		`RegionUsEast1 Region = "us-east-1"`,
		`RegionEuWest1 Region = "eu-west-1"`,
		"func WithRegion(v Region) Option {",
		// No enum, so no named type and no constants — a bare string is all the spec supports.
		"func WithVersion(v string) Option {",
		`BaseURLTemplate: "https://{region}.api.example.com/{version}"`,
		`"region":  "us-east-1"`,
		`"version": "v2"`,
		// The description carries into the doc comment, since that is where a caller reads it.
		"// Data residency.",
	} {
		if !containsNormalized(client, want) {
			t.Errorf("client.go is missing %q", want)
		}
	}

	// A resolved BaseURL alongside the template would win in the runtime and pin the defaults,
	// making every With* option silently useless.
	if strings.Contains(client, "BaseURL:") {
		t.Errorf("a templated server must not also set BaseURL:\n%s", client)
	}
}

// TestUntemplatedServerKeepsAPlainBaseURL is the other half: nothing changes for the common case.
func TestUntemplatedServerKeepsAPlainBaseURL(t *testing.T) {
	client := emitFiles(t, testIR(t, minimalIR), `{"packageName":"acme"}`)["client.go"]
	if !containsNormalized(client, `BaseURL: "https://api.acme.com"`) {
		t.Errorf("expected a plain BaseURL:\n%s", client)
	}
	if strings.Contains(client, "BaseURLTemplate") {
		t.Errorf("an untemplated server must not set BaseURLTemplate:\n%s", client)
	}
}

// TestSchemasFileIsEmittedForPrimitiveOnlyResponses pins a spec shape the corpus does not have.
//
// The emit gate read the *named type* table, but `responseSchemas` lives in the same file and is
// referenced by any method whose response has a descriptor. A spec returning `[]string` has no named
// types and a non-empty response map, so the file was skipped and the SDK referenced two undefined
// symbols. Every corpus spec declares named types, which is why it compiled everywhere.
func TestSchemasFileIsEmittedForPrimitiveOnlyResponses(t *testing.T) {
	files := emitFiles(t, testIR(t, primitiveResponseIR), `{"packageName":"acme"}`)
	schemas, ok := files["schemas.go"]
	if !ok {
		t.Fatalf("schemas.go was not emitted; files: %v", keysOf(files))
	}
	if !strings.Contains(schemas, "responseSchemas = core.MustParseSchemaTable") {
		t.Errorf("schemas.go does not define responseSchemas:\n%s", schemas)
	}
}

// containsNormalized reports whether source contains want, ignoring how gofmt aligned it.
//
// gofmt pads struct field values into columns, so `BaseURL: "x"` is emitted as `BaseURL:   "x"`. An
// exact match makes a test depend on how many other fields happen to be in the literal.
func containsNormalized(source, want string) bool {
	collapse := func(text string) string {
		for strings.Contains(text, "  ") {
			text = strings.ReplaceAll(text, "  ", " ")
		}
		return text
	}
	return strings.Contains(collapse(source), collapse(want))
}

func keysOf(files map[string]string) []string {
	out := make([]string, 0, len(files))
	for name := range files {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

const primitiveResponseIR = `{
  "irVersion": "1.5.0",
  "service": {
    "name": {"tokens":["acme"]}, "displayName": "Acme", "version": "1.0", "docs": {},
    "servers": [{"url":"https://api.acme.com","default":true,"docs":{}}],
    "auth": [], "constantHeaders": {}
  },
  "types": [],
  "resources": [{
    "id": "widgets", "name": {"tokens":["widgets"]}, "docs": {}, "subresources": [],
    "methods": [{
      "name": {"tokens":["list"]},
      "http": {"method":"get","path":"/widgets","pathParams":[],"queryParams":[],"headerParams":[]},
      "response": {"kind":"json","type":{"kind":"array","items":{"kind":"primitive","type":"string"}}},
      "deprecated": false, "docs": {}
    }]
  }],
  "errors": {"byStatus": []}, "pagination": []
}`
