import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { BRAND, BRAND_NAME, attribution, extensionKey } from './branding.js';

const REPO_ROOT = new URL('../../../', import.meta.url).pathname;

/**
 * Every source file under `packages/` that could put this project's name into generated output.
 *
 * Every language the project generates in, not just TypeScript. Scanning only `.ts` was a real hole: the Go target is
 * written in Go, so the guard could not see it, and it accumulated five copies of
 * `"Code generated by besdk. DO NOT EDIT."` — landing the name in the one place it must never
 * appear, a file a consumer commits. A rule enforced in one language of a three-language project is
 * not enforced.
 *
 * `.venv` and Go build caches are skipped along with `node_modules` and `dist`; a vendored runtime
 * copy under a `vendor` directory is not ours to police.
 *
 * `.php` was missing from this list for as long as PHP has been a target, which is the same failure the
 * docs guard had: a rule enforced in five languages of a six-language project is not enforced. It was found
 * when a multipart boundary prefixed with the brand landed in three runtimes and only two of them were
 * reported.
 */
const SCANNED_EXTENSIONS = ['.ts', '.py', '.go', '.java', '.cs', '.php'];
const SKIPPED_DIRECTORIES = new Set(['node_modules', 'dist', '.venv', 'vendor', '__pycache__']);

function sourceFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (SKIPPED_DIRECTORIES.has(entry)) continue;
      if (statSync(full).isDirectory()) {
        walk(full);
        continue;
      }
      if (!SCANNED_EXTENSIONS.some((extension) => entry.endsWith(extension))) continue;
      // Test files may name the brand freely: they assert on it, and they are not shipped.
      if (/\.test\.(ts|go)$|_test\.go$|^test_|_test\.py$|Test\.java$|Tests?\.cs$|Test\.php$/.test(entry))
        continue;
      out.push(full);
    }
  };
  walk(join(REPO_ROOT, 'packages'));
  return out;
}

/**
 * Strip comments and docstrings, since prose mentions are legitimate.
 *
 * Line-comment syntax differs per language, and Python's triple-quoted docstring is *also* a string
 * literal — so a naive literal match would flag every module docstring that explains what the
 * project is.
 */
function stripProse(file: string, text: string): string {
  if (file.endsWith('.py')) {
    return text
      .replace(/"""[\s\S]*?"""/g, '""')
      .replace(/'''[\s\S]*?'''/g, "''")
      .replace(/#.*$/gm, '');
  }
  return text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
}

describe('derived strings', () => {
  it('derives every user-facing name from the brand', () => {
    // The point of the module: rename `BRAND_NAME` and all of these follow. Asserted so a future
    // edit cannot quietly hardcode one of them back.
    expect(BRAND.configFile).toBe(`${BRAND_NAME}.yaml`);
    expect(BRAND.stateDir).toBe(`.${BRAND_NAME}`);
    expect(BRAND.extensionPrefix).toBe(`x-${BRAND_NAME}`);
    expect(BRAND.targetPrefix).toBe(`${BRAND_NAME}-target-`);
    // The one string here that must *not* follow a rename: a target in another language hardcodes
    // it, so it is a promise to third parties rather than an internal detail.
    expect(BRAND.handshakeFlag).not.toContain(BRAND_NAME);
    expect(extensionKey('group')).toBe(`x-${BRAND_NAME}-group`);
    expect(attribution()).toContain(BRAND_NAME);
  });
});

describe('no hardcoded brand in string literals', () => {
  /**
   * The brand may appear in prose — comments, JSDoc, docs — but never inside a quoted string in
   * source, because that is what a rename would miss.
   *
   * `besdk` is a working title, so this guard is what makes changing it a one-line edit rather
   * than an archaeology exercise.
   */
  it('finds none outside branding.ts', () => {
    const offenders: string[] = [];

    for (const file of sourceFiles()) {
      if (file.endsWith('branding.ts')) continue;
      const code = stripProse(file, readFileSync(file, 'utf8'));

      // Quoted or backticked literals containing the brand. Import specifiers are excluded
      // separately below, since workspace package names cannot be abstracted.
      const literals = code.match(/(['"`])[^'"`\n]*?\b\w*besdk\w*[^'"`\n]*?\1/gi) ?? [];
      for (const literal of literals) {
        // `@besdk/…` package specifiers are unavoidable literals; the rename procedure in
        // SPEC.md covers them, and `brand:packages` lists them.
        if (/@besdk\//.test(literal)) continue;
        // Python and Go module identity: `besdk_runtime`, `besdk_target_python`,
        // `github.com/besdk/…`. Same category as the `@besdk/…` specifiers — a package's own name
        // is a literal no constant can abstract, and step 2 of the rename procedure covers it.
        if (/besdk[_-](runtime|target)|github\.com\/besdk|besdk-target-/.test(literal)) continue;
        // Java package identity: the runtime's own package is `besdk.runtime`, and the target rewrites it to
        // `<namespace>.core` on vendoring — so unlike Go and PHP, where the source package could simply be
        // named `core`, Java requires the package to match its directory and the rewrite is unavoidable.
        // Java package identity, in dotted *and* path form: the runtime's own package is `besdk.runtime` and
        // lives at `besdk/runtime`, and the target rewrites it to `<namespace>.core` on vendoring — so unlike
        // Go and PHP, where the source package could simply be named `core`, Java requires the package to
        // match its directory and the rewrite is unavoidable.
        if (/besdk[./]runtime|besdk[./]target|dev\.besdk/.test(literal)) continue;
        // C# assembly and namespace identity: `Besdk.Runtime`. Same category as every other language's package
        // name — a literal no constant can abstract, covered by step 2 of the rename procedure.
        if (/Besdk\.(Runtime|Target)/.test(literal)) continue;
        // PHP namespace identity: the runtime's own namespace is `Besdk\Runtime`, and the target rewrites
        // it to `<Namespace>\Core` on vendoring. Same category as Java's dotted package and Go's module
        // path — a package's own name is a literal no constant can abstract.
        if (/Besdk\\+(Runtime|Target)/.test(literal)) continue;
        offenders.push(`${file.replace(REPO_ROOT, '')}: ${literal}`);
      }
    }

    expect(offenders).toEqual([]);
  });
});

describe('generated output', () => {
  it('does not name the generator in any exported identifier', () => {
    // A generator-branded class or type would put this tool's name into consumers' code, making a
    // rename a breaking change for every SDK ever produced. The runtime's base error is
    // role-named (`SDKError`) precisely so that cannot happen.
    const runtime = join(REPO_ROOT, 'packages/runtime-typescript/src');
    for (const entry of readdirSync(runtime)) {
      if (!entry.endsWith('.ts') || entry.endsWith('.test.ts')) continue;
      const text = readFileSync(join(runtime, entry), 'utf8');
      const exported = text.match(/^export\s+(?:abstract\s+)?(?:class|interface|type|function|const)\s+(\w+)/gm) ?? [];
      for (const declaration of exported) {
        expect(declaration.toLowerCase(), `${entry}: ${declaration}`).not.toContain(
          BRAND_NAME.toLowerCase(),
        );
      }
    }
  });
});
