/**
 * Project branding — every user-facing occurrence of the tool's name, in one place.
 *
 * **`graft` is a working title.** Renaming a tool is normally expensive because the name leaks
 * into filenames, extension keys, state directories, help text, and — worst — into the generated
 * output that other people's code depends on. This module exists so that a rename is a one-line
 * change plus a mechanical pass over package names, rather than an archaeology exercise.
 *
 * What is *deliberately not* here:
 *
 *   - **Workspace package names** (`@graft/core` and friends) and import specifiers. Those are
 *     literals in `package.json` and `import` statements; no constant can abstract them. They are
 *     a one-time find-and-replace; `pnpm test` in this package fails on any that is missed.
 *   - **The base error class in generated SDKs.** That one is not centralized, it is *eliminated*:
 *     the runtime exports `SDKError`, named for its role. A generator-branded class would put this
 *     tool's name into every consumer's catch block, making a rename here a breaking change for
 *     every SDK ever produced. Generated code aliases it to `<ClientName>Error` instead, so the
 *     brand a user sees is *their own*.
 *
 * The distinction that matters: a name in *our* files is an inconvenience; a name in *generated*
 * files is a compatibility promise. Only the first kind belongs in a constant.
 */

/** The project name, lowercase. Used for the CLI binary and in messages. */
export const BRAND_NAME = 'graft';

/** Title-case form, for prose and headings. */
export const BRAND_TITLE = 'Graft';

/** Where the project lives, for attribution in generated READMEs. */
export const BRAND_HOMEPAGE = 'https://github.com/papervine/graft';

/**
 * Every derived user-facing string.
 *
 * Computed from {@link BRAND_NAME} rather than written out, so a rename cannot leave one of them
 * behind — which is the failure mode that makes renames expensive in the first place.
 */
export const BRAND = {
  name: BRAND_NAME,
  title: BRAND_TITLE,
  homepage: BRAND_HOMEPAGE,

  /** Config file basename, e.g. `graft.yaml`. */
  configFile: `${BRAND_NAME}.yaml`,

  /** Directory holding IR baselines, e.g. `.graft`. Committed, not ignored. */
  stateDir: `.${BRAND_NAME}`,

  /** Vendor extension prefix without a trailing dash, e.g. `x-graft`. */
  extensionPrefix: `x-${BRAND_NAME}`,

  /** Prefix by which third-party target executables are discovered, e.g. `graft-target-`. */
  targetPrefix: `${BRAND_NAME}-target-`,

  /**
   * Flag a target must answer with a handshake.
   *
   * Deliberately **not** derived from {@link BRAND_NAME}, unlike everything else here. A target may
   * be written in any language, so it cannot import this module — it has to hardcode this flag. That
   * makes the flag something *third parties* depend on, and a rename would break every target ever
   * written against it. Which is the same argument that keeps this project's name out of `SDKError`,
   * applied to the plugin boundary: a name others must repeat back is a compatibility promise.
   *
   * Nothing else in the protocol has this property. The IR and the manifest arrive as JSON, so a
   * target reads field names rather than writing them, and the brand strings a target *emits* are
   * carried in `TargetInput.brand` for exactly this reason.
   */
  handshakeFlag: '--sdk-target-protocol',
} as const;

/**
 * Extension prefixes from *previous* names of this project.
 *
 * Empty today because `graft` has had no release. If the project is ever renamed after specs in
 * the wild carry `x-graft-*`, the old prefix belongs here: those annotations state the API owner's
 * intent, and a rename on our side must not silently stop honouring them. Reading a superseded
 * prefix is the same argument as reading another vendor's (SPEC.md §3.1.5), applied to our own
 * history.
 */
export const LEGACY_EXTENSION_PREFIXES: readonly string[] = [];

/** Build an extension key: `extensionKey('group')` → `x-graft-group`. */
export function extensionKey(suffix: string): string {
  return `${BRAND.extensionPrefix}-${suffix}`;
}

/** Attribution line for generated READMEs. */
export function attribution(): string {
  return `_Generated by [${BRAND.title}](${BRAND.homepage}). Edit the spec or \`${BRAND.configFile}\`, not this package._`;
}

/**
 * The header line at the top of every generated source file.
 *
 * `DO NOT EDIT` is the exact phrase Go tooling looks for: `gofmt`, `go vet`, and most linters skip a
 * file whose first line matches `^// Code generated .* DO NOT EDIT\.$`. Deviating from it would make
 * generated Go code lint like hand-written code, which is a real cost for no gain.
 */
export function generatedNotice(): string {
  return `Code generated by ${BRAND.name}. DO NOT EDIT.`;
}

/**
 * The brand strings a target needs, sent to every target in {@link TargetInput}.
 *
 * Exists because the no-hardcoded-name rule is enforced by a TypeScript test, and two of the three
 * blessed targets are not written in TypeScript. A Go target cannot import this module, so left to
 * itself it hardcodes `"Code generated by graft"` — which is the one place the name must never
 * appear, since it lands in files consumers commit. Carrying the strings over the protocol makes the
 * rule enforceable across languages, and makes a third-party target correct without being asked.
 */
export function brandPayload(): {
  name: string;
  title: string;
  homepage: string;
  configFile: string;
  generatedNotice: string;
  attribution: string;
} {
  return {
    name: BRAND.name,
    title: BRAND.title,
    homepage: BRAND.homepage,
    configFile: BRAND.configFile,
    generatedNotice: generatedNotice(),
    attribution: attribution(),
  };
}
