"""Unit tests for the Python target.

Every test here corresponds to a defect found by reading generated output or by running it — the
sixteen listed in SPEC.md §3.3.3. A generator's bugs are almost never "it crashed"; they are "it
emitted something plausible and wrong", so each of these pins a specific wrong thing.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from graft_target_python.__main__ import HANDSHAKE_FLAG
from graft_target_python.builder import Class, Function, Module, Param, literal_union
from graft_target_python.emit import PythonEmitter

# What the core sends in `TargetInput.brand`. Required rather than defaulted, because a hardcoded
# fallback in the target is exactly what carrying it over the protocol exists to prevent.
BRAND = {
    "name": "graft",
    "title": "graft",
    "homepage": "https://example.invalid",
    "configFile": "graft.yaml",
    "generatedNotice": "Code generated by graft. DO NOT EDIT.",
    "attribution": "_Generated by graft._",
}
from graft_target_python.naming import (  # noqa: E402
    module_name,
    safe_attribute,
    safe_identifier,
    safe_method_name,
    snake,
    snake_from_mixed,
    unique_attribute,
)

DOCS: dict[str, Any] = {}


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------


class TestNaming:
    def test_tokens_become_snake_case(self) -> None:
        assert snake(["user", "id"]) == "user_id"

    @pytest.mark.parametrize(
        ("wire", "expected"),
        [
            # `id` and `type` are the two commonest field names in real APIs and are never emitted
            # as annotations, so suffixing them would mark almost every model as machine-made.
            ("id", "id"),
            ("type", "type"),
            # Keywords are unavoidable — `self.from` is a syntax error.
            ("from", "from_"),
            ("class", "class_"),
            # These *are* emitted as annotations, so a field with the name shadows it class-wide.
            ("object", "object_"),
            ("str", "str_"),
            # A pydantic BaseModel method. GitHub has a field called `validate`.
            ("validate", "validate_"),
        ],
    )
    def test_attribute_names(self, wire: str, expected: str) -> None:
        assert safe_attribute(wire) == expected

    def test_method_names_keep_builtins(self) -> None:
        # `client.widgets.list()` is correct; `list_()` is the tell-tale generated-code smell.
        assert safe_method_name("list") == "list"
        assert safe_method_name("delete") == "delete"
        assert safe_method_name("import") == "import_"

    def test_locals_avoid_builtins(self) -> None:
        # Stricter than attributes: a bare `list` inside a function body really does shadow it.
        assert safe_identifier("list") == "list_"
        assert safe_identifier("id") == "id_"

    def test_colliding_attributes_are_disambiguated(self) -> None:
        # Two GitHub properties both sanitise to `_1`; the second silently replaced the first.
        taken: set[str] = set()
        assert unique_attribute("1", taken) == "_1"
        assert unique_attribute("1", taken) == "_1_2"

    @pytest.mark.parametrize(
        ("resource_id", "expected"),
        [
            # Twilio's resource ids are PascalCase, which produced `Api20100401Address.py`.
            ("Api20100401Address", "api20100401_address"),
            ("orgs.invoices", "orgs_invoices"),
            ("HTTPServer", "http_server"),
            ("already_snake", "already_snake"),
        ],
    )
    def test_module_names_are_pep8(self, resource_id: str, expected: str) -> None:
        assert module_name(resource_id) == expected

    def test_snake_from_mixed_handles_capital_runs(self) -> None:
        assert snake_from_mixed("parseHTTPResponse") == "parse_http_response"


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


class TestBuilder:
    def test_docstring_escapes_a_trailing_quote(self) -> None:
        # Stripe: `The user ID, if type is set to "user"`. A trailing quote made the closing
        # delimiter four quotes, an unterminated string.
        module = Module()
        module.add(Class(name="X", docstring='ends with a quote "user"'))
        rendered = module.render()
        compile(rendered, "<test>", "exec")  # the real assertion: it parses

    def test_docstring_escapes_embedded_triple_quotes(self) -> None:
        module = Module()
        module.add(Class(name="X", docstring='has """ inside'))
        compile(module.render(), "<test>", "exec")

    def test_long_docstrings_are_wrapped(self) -> None:
        # `ruff format` does not reflow prose, so an unwrapped description fails the line limit.
        module = Module()
        module.add(Class(name="X", docstring="word " * 80))
        for line in module.render().split("\n"):
            assert len(line) <= 100, line

    def test_indented_blocks_are_not_reflowed(self) -> None:
        # Rewrapping a code sample is how a generator turns a working example into a broken one.
        code = "    client.widgets.list(limit=50, offset=0, order='desc', extra='keep this exact')"
        module = Module()
        module.add(Class(name="X", docstring=f"Example:\n\n{code}"))
        assert code in module.render()

    def test_markdown_list_items_are_wrapped_and_keep_their_marker(self) -> None:
        # GitHub's descriptions are full of two-space bullets; treating them as code left 222
        # unwrapped lines. The bullet sits after a summary because the *first* line of a docstring
        # is deliberately un-indented — PEP 257 puts it against the opening quotes.
        module = Module()
        module.add(Class(name="X", docstring="Summary.\n\n" + " - " + ("word " * 40)))
        rendered = module.render()
        assert " - word" in rendered
        # A wrapped continuation is indented under the text, so markdown still reads it as one item.
        assert "   word" in rendered
        for line in rendered.split("\n"):
            assert len(line) <= 100, line

    def test_imports_are_grouped_and_deduplicated(self) -> None:
        module = Module()
        module.use_future_annotations()
        module.import_from("typing", "Literal")
        module.import_from("typing", "Literal", "TypeAlias")
        module.import_from("pydantic", "BaseModel")
        module.import_from("._core", "BaseClient")
        rendered = module.render()
        assert rendered.count("from typing import") == 1
        assert "from typing import Literal, TypeAlias" in rendered
        assert rendered.index("from __future__") < rendered.index("from typing")
        assert rendered.index("from typing") < rendered.index("from pydantic")
        assert rendered.index("from pydantic") < rendered.index("from ._core")

    def test_urllib_is_stdlib_not_third_party(self) -> None:
        module = Module()
        module.import_from("urllib.parse", "quote")
        module.import_from("pydantic", "BaseModel")
        rendered = module.render()
        assert rendered.index("urllib.parse") < rendered.index("pydantic")

    def test_keyword_only_marker_is_emitted_once(self) -> None:
        fn = Function(
            name="f",
            params=[
                Param("self"),
                Param("a", annotation="str"),
                Param("b", annotation="str", default="None", keyword_only=True),
                Param("c", annotation="str", default="None", keyword_only=True),
            ],
            returns="None",
            body=["pass"],
        )
        signature = fn.render()[0]
        assert signature.count("*") == 1
        assert signature == "def f(self, a: str, *, b: str = None, c: str = None) -> None:"

    def test_open_enums_union_with_str(self) -> None:
        # A server adds a value without warning; an exhaustive type would make that a decode failure.
        assert literal_union(["a", "b"], open_ended=True) == "Literal['a', 'b'] | str"
        assert literal_union(["a"], open_ended=False) == "Literal['a']"

    def test_class_trailing_text_stays_inside_the_body(self) -> None:
        # The preservation markers must sit inside the class, or a user's method between them is a
        # top-level syntax error.
        cls = Class(name="X", methods=[Function(name="m", body=["pass"])], trailing=["# region x"])
        rendered = "\n".join(cls.render())
        assert "    # region x" in rendered
        compile(rendered, "<test>", "exec")


# ---------------------------------------------------------------------------
# Emission, end to end
# ---------------------------------------------------------------------------


def ir_with(
    *,
    types: list[dict[str, Any]] | None = None,
    resources: list[dict[str, Any]] | None = None,
    pagination: list[dict[str, Any]] | None = None,
    errors: dict[str, Any] | None = None,
    servers: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "irVersion": "1.2.0",
        "service": {
            "name": {"tokens": ["acme"]},
            "displayName": "Acme",
            "version": "1.0",
            "docs": DOCS,
            "servers": servers
            or [
                {
                    "url": "https://api.acme.com",
                    "default": True,
                    "docs": DOCS,
                    "variables": [],
                }
            ],
            "auth": [{"kind": "bearer", "docs": DOCS}],
            "constantHeaders": {},
        },
        "types": types or [],
        "resources": resources or [],
        "errors": errors or {"byStatus": []},
        "pagination": pagination or [],
    }


def field(
    name: str, type_ref: dict[str, Any], *, required: bool = True, wire: str | None = None
) -> dict[str, Any]:
    return {
        "name": {"tokens": name.split("_")},
        "wireName": wire or name,
        "type": type_ref,
        "required": required,
        "serverOwned": False,
        "readOnly": False,
        "writeOnly": False,
        "deprecated": False,
        "docs": DOCS,
    }


STR = {"kind": "primitive", "type": "string"}


def emit(ir: dict[str, Any]) -> dict[str, str]:
    files = PythonEmitter(ir, {"packageName": "acme"}, BRAND).emit({})
    return {f["path"]: f["contents"] for f in files}


class TestEmission:
    def test_read_models_are_pydantic_and_write_models_are_typeddicts(self) -> None:
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "Widget",
                    "name": {"tokens": ["widget"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("id", STR)],
                },
                {
                    "kind": "object",
                    "id": "WidgetCreate",
                    "name": {"tokens": ["widget", "create"]},
                    "docs": DOCS,
                    "role": "create",
                    "cyclic": False,
                    "fields": [field("name", STR), field("note", STR, required=False)],
                },
            ]
        )
        models = emit(ir)["src/acme/models.py"]
        assert "class Widget(BaseModel):" in models
        assert "class WidgetCreate(TypedDict):" in models
        # `NotRequired` for absence, and from typing_extensions so the declared 3.10 floor holds.
        assert "note: NotRequired[str]" in models
        assert "from typing_extensions import NotRequired, TypedDict" in models

    def test_a_model_named_field_does_not_shadow_pydantic_field(self) -> None:
        # Both Stripe and Twilio declare one; it produced 393 mypy errors from a single collision.
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "Field",
                    "name": {"tokens": ["field"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("py_name", STR, wire="wireName")],
                },
            ]
        )
        models = emit(ir)["src/acme/models.py"]
        assert "class Field(" not in models
        assert "class FieldModel(" in models

    def test_request_bodies_are_not_dropped(self) -> None:
        # The IR field is `body`; reading `request` produced methods that could send nothing.
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "WidgetCreate",
                    "name": {"tokens": ["widget", "create"]},
                    "docs": DOCS,
                    "role": "create",
                    "cyclic": False,
                    "fields": [field("name", STR)],
                }
            ],
            resources=[
                {
                    "id": "widgets",
                    "name": {"tokens": ["widgets"]},
                    "docs": DOCS,
                    "subresources": [],
                    "methods": [
                        {
                            "name": {"tokens": ["create"]},
                            "operationId": "createWidget",
                            "docs": DOCS,
                            "deprecated": False,
                            "http": {"verb": "post", "path": "/widgets", "params": []},
                            "body": {
                                "type": {"kind": "named", "id": "WidgetCreate"},
                                "contentType": "application/json",
                                "required": True,
                            },
                            "response": {"kind": "empty", "statusCode": 204},
                        }
                    ],
                }
            ],
        )
        widgets = emit(ir)["src/acme/widgets.py"]
        assert "body: WidgetCreate" in widgets
        assert "body=body" in widgets

    def test_pagination_is_detected_from_pagination_id(self) -> None:
        # The IR field is `paginationId`; reading `pagination` silently truncated every list to one
        # page while typechecking perfectly.
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "Widget",
                    "name": {"tokens": ["widget"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("id", STR)],
                }
            ],
            pagination=[
                {
                    "id": "cursor",
                    "style": "cursor",
                    "limitParam": "limit",
                    "cursorParam": "cursor",
                    "cursorSource": {"kind": "body", "path": ["next_cursor"]},
                    "itemsSource": {"kind": "body", "path": ["data"]},
                }
            ],
            resources=[
                {
                    "id": "widgets",
                    "name": {"tokens": ["widgets"]},
                    "docs": DOCS,
                    "subresources": [],
                    "methods": [
                        {
                            "name": {"tokens": ["list"]},
                            "operationId": "listWidgets",
                            "docs": DOCS,
                            "deprecated": False,
                            "paginationId": "cursor",
                            "http": {"verb": "get", "path": "/widgets", "params": []},
                            "response": {
                                "kind": "json",
                                "statusCode": 200,
                                "type": {
                                    "kind": "array",
                                    "items": {"kind": "named", "id": "Widget"},
                                },
                            },
                        }
                    ],
                }
            ],
        )
        widgets = emit(ir)["src/acme/widgets.py"]
        assert "-> Paginator[Widget]:" in widgets
        assert "-> AsyncPaginator[Widget]:" in widgets
        assert "advance_cursor('cursor')" in widgets
        # The async paginator method must not be a coroutine: `async for` drives it.
        assert "async def list" not in widgets

    def test_a_union_item_type_imports_its_members_not_its_rendering(self) -> None:
        # Stripe has a page whose item is a union; the rendered string produced
        # `from .models import BankAccount | Card`, a syntax error.
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "Bank",
                    "name": {"tokens": ["bank"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("id", STR)],
                },
                {
                    "kind": "object",
                    "id": "Card",
                    "name": {"tokens": ["card"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("id", STR)],
                },
            ],
            pagination=[
                {
                    "id": "cursor",
                    "style": "cursor",
                    "limitParam": "limit",
                    "cursorParam": "cursor",
                    "cursorSource": {"kind": "body", "path": ["next_cursor"]},
                    "itemsSource": {"kind": "body", "path": ["data"]},
                }
            ],
            resources=[
                {
                    "id": "sources",
                    "name": {"tokens": ["sources"]},
                    "docs": DOCS,
                    "subresources": [],
                    "methods": [
                        {
                            "name": {"tokens": ["list"]},
                            "operationId": "listSources",
                            "docs": DOCS,
                            "deprecated": False,
                            "paginationId": "cursor",
                            "http": {"verb": "get", "path": "/sources", "params": []},
                            "response": {
                                "kind": "json",
                                "statusCode": 200,
                                "type": {
                                    "kind": "array",
                                    "items": {
                                        "kind": "union",
                                        "variants": [
                                            {"kind": "named", "id": "Bank"},
                                            {"kind": "named", "id": "Card"},
                                        ],
                                    },
                                },
                            },
                        }
                    ],
                }
            ],
        )
        sources = emit(ir)["src/acme/sources.py"]
        assert "from .models import Bank, Card" in sources
        compile(sources, "<test>", "exec")

    def test_a_query_parameter_named_query_does_not_capture_the_local(self) -> None:
        # Stripe has one. The body's `query` dict was shadowed by the parameter.
        ir = ir_with(
            resources=[
                {
                    "id": "search",
                    "name": {"tokens": ["search"]},
                    "docs": DOCS,
                    "subresources": [],
                    "methods": [
                        {
                            "name": {"tokens": ["run"]},
                            "operationId": "search",
                            "docs": DOCS,
                            "deprecated": False,
                            "http": {
                                "verb": "get",
                                "path": "/search",
                                "params": [
                                    {
                                        "name": {"tokens": ["query"]},
                                        "wireName": "query",
                                        "location": "query",
                                        "type": STR,
                                        "required": True,
                                        "deprecated": False,
                                        "docs": DOCS,
                                    }
                                ],
                            },
                            "response": {"kind": "empty", "statusCode": 204},
                        }
                    ],
                }
            ],
        )
        search = emit(ir)["src/acme/search.py"]
        compile(search, "<test>", "exec")
        # The parameter keeps the natural name; the temporary is the one that moves.
        assert "query: str" in search
        assert "query_: dict[str, object]" in search

    def test_a_method_named_list_qualifies_the_list_annotation(self) -> None:
        # `def list(...) -> list[Widget]` makes mypy read the return type as the method itself.
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "Widget",
                    "name": {"tokens": ["widget"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("id", STR)],
                }
            ],
            resources=[
                {
                    "id": "widgets",
                    "name": {"tokens": ["widgets"]},
                    "docs": DOCS,
                    "subresources": [],
                    "methods": [
                        {
                            "name": {"tokens": ["list"]},
                            "operationId": "listWidgets",
                            "docs": DOCS,
                            "deprecated": False,
                            "http": {"verb": "get", "path": "/widgets", "params": []},
                            "response": {
                                "kind": "json",
                                "statusCode": 200,
                                "type": {
                                    "kind": "array",
                                    "items": {"kind": "named", "id": "Widget"},
                                },
                            },
                        }
                    ],
                }
            ],
        )
        widgets = emit(ir)["src/acme/widgets.py"]
        assert "-> builtins.list[Widget]:" in widgets
        assert "import builtins" in widgets
        # The method itself keeps the idiomatic name.
        assert "def list(" in widgets

    def test_the_client_accepts_an_injected_http_client(self) -> None:
        # Without it a caller cannot test their own code against the SDK.
        client = emit(ir_with())["src/acme/_client.py"]
        assert "http_client: httpx.Client | None = None" in client
        assert "http_client: httpx.AsyncClient | None = None" in client
        assert "http_client=http_client," in client

    def test_path_parameters_are_escaped(self) -> None:
        # An id containing `/` would otherwise address a different endpoint.
        ir = ir_with(
            resources=[
                {
                    "id": "widgets",
                    "name": {"tokens": ["widgets"]},
                    "docs": DOCS,
                    "subresources": [],
                    "methods": [
                        {
                            "name": {"tokens": ["get"]},
                            "operationId": "getWidget",
                            "docs": DOCS,
                            "deprecated": False,
                            "http": {
                                "verb": "get",
                                "path": "/widgets/{id}",
                                "params": [
                                    {
                                        "name": {"tokens": ["id"]},
                                        "wireName": "id",
                                        "location": "path",
                                        "type": STR,
                                        "required": True,
                                        "deprecated": False,
                                        "docs": DOCS,
                                    }
                                ],
                            },
                            "response": {"kind": "empty", "statusCode": 204},
                        }
                    ],
                }
            ],
        )
        widgets = emit(ir)["src/acme/widgets.py"]
        assert "encode_path(id_)" in widgets

    def test_package_version_is_pep440(self) -> None:
        # Stripe's API version is `2026-07-29.dahlia`; ruff could not parse the pyproject at all,
        # so it silently fell back to its default configuration.
        ir = ir_with()
        ir["service"]["version"] = "2026-07-29.dahlia"
        pyproject = emit(ir)["pyproject.toml"]
        assert 'version = "2026.0"' in pyproject or 'version = "0.1.0"' in pyproject
        assert "dahlia" not in pyproject

    def test_error_names_the_runtime_owns_are_not_regenerated(self) -> None:
        # GitHub declares a 503 named `InternalServerError`, which the runtime already exports.
        ir = ir_with(
            errors={
                "byStatus": [
                    {
                        "statusCode": 503,
                        "name": {"tokens": ["internal", "server", "error"]},
                        "retryable": True,
                        "docs": DOCS,
                    },
                    {
                        "statusCode": 418,
                        "name": {"tokens": ["teapot", "error"]},
                        "retryable": False,
                        "docs": DOCS,
                    },
                ]
            }
        )
        files = emit(ir)
        errors = files["src/acme/errors.py"]
        assert "class TeapotError(" in errors
        assert "class InternalServerError(" not in errors
        # And the entry point must not name it twice — once from the runtime, once from `.errors`.
        entry = files["src/acme/__init__.py"]
        assert entry.count("InternalServerError") == 2  # the import, and the `__all__` entry
        assert "from .errors import TeapotError" in entry

    def test_no_module_uses_Any(self) -> None:
        # `Any` disables the mypy gate that justifies the whole pipeline.
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "Loose",
                    "name": {"tokens": ["loose"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("blob", {"kind": "unknown"})],
                }
            ],
        )
        models = emit(ir)["src/acme/models.py"]
        assert "blob: object" in models
        assert ": Any" not in models

    def test_every_emitted_module_is_valid_python(self) -> None:
        ir = ir_with(
            types=[
                {
                    "kind": "object",
                    "id": "Widget",
                    "name": {"tokens": ["widget"]},
                    "docs": DOCS,
                    "role": "read",
                    "cyclic": False,
                    "fields": [field("id", STR)],
                }
            ],
            resources=[
                {
                    "id": "widgets",
                    "name": {"tokens": ["widgets"]},
                    "docs": DOCS,
                    "subresources": [
                        {
                            "id": "widgets.parts",
                            "name": {"tokens": ["parts"]},
                            "docs": DOCS,
                            "subresources": [],
                            "methods": [],
                        }
                    ],
                    "methods": [
                        {
                            "name": {"tokens": ["get"]},
                            "operationId": "getWidget",
                            "docs": DOCS,
                            "deprecated": False,
                            "http": {
                                "verb": "get",
                                "path": "/widgets/{id}",
                                "params": [
                                    {
                                        "name": {"tokens": ["id"]},
                                        "wireName": "id",
                                        "location": "path",
                                        "type": STR,
                                        "required": True,
                                        "deprecated": False,
                                        "docs": DOCS,
                                    }
                                ],
                            },
                            "response": {
                                "kind": "json",
                                "statusCode": 200,
                                "type": {"kind": "named", "id": "Widget"},
                            },
                        }
                    ],
                }
            ],
        )
        for path, contents in emit(ir).items():
            if path.endswith(".py"):
                compile(contents, path, "exec")


# ---------------------------------------------------------------------------
# Protocol
# ---------------------------------------------------------------------------


class TestProtocol:
    def test_handshake_declares_gates_and_a_line_comment(self) -> None:
        result = subprocess.run(
            [sys.executable, "-m", "graft_target_python", HANDSHAKE_FLAG],
            capture_output=True,
            text=True,
            cwd=str(Path(__file__).resolve().parents[1] / "src"),
            check=True,
        )
        handshake = json.loads(result.stdout)
        assert handshake["name"] == "python"
        # `#` is what lets the core find preservation markers without knowing Python.
        assert handshake["lineComment"] == "#"
        gate_names = [g["name"] for g in handshake["gates"]]
        assert "mypy --strict" in gate_names
        # A formatter's exit code is not a verdict; the typechecker's is.
        kinds = {g["name"]: g.get("kind") for g in handshake["gates"]}
        assert kinds["ruff format"] == "fix"
        assert kinds["mypy --strict"] == "verify"
        # The typechecker must not be skippable.
        optional = {g["name"]: g.get("optional", False) for g in handshake["gates"]}
        assert optional["mypy --strict"] is False

    def test_empty_stdin_is_an_error_not_a_traceback(self) -> None:
        result = subprocess.run(
            [sys.executable, "-m", "graft_target_python"],
            input="",
            capture_output=True,
            text=True,
            cwd=str(Path(__file__).resolve().parents[1] / "src"),
        )
        assert result.returncode == 2
        assert "expected IR JSON" in result.stderr
        assert "Traceback" not in result.stderr


class TestIdempotencyHeader:
    """Guards the threading, not the behaviour.

    The runtime already honoured a custom header; the target simply never passed one on, so
    `idempotencyHeader` in graft.yaml was accepted, validated, and silently discarded. That failure
    mode leaves every gate green — the SDK imports, typechecks, and formats — which is why it needs a
    test naming the config key rather than a review.
    """

    def test_a_configured_header_reaches_the_client(self) -> None:
        files = PythonEmitter(
            ir_with(), {"packageName": "acme", "idempotencyHeader": "X-Idempotency-Key"}, BRAND
        ).emit({})
        client = next(f["contents"] for f in files if f["path"].endswith("_client.py"))
        # Quote-agnostic: the emitter uses repr(), ruff format normalises to double quotes later.
        assert "idempotency_header=" in client
        assert "X-Idempotency-Key" in client

    def test_no_configuration_leaves_the_runtime_default(self) -> None:
        files = PythonEmitter(ir_with(), {"packageName": "acme"}, BRAND).emit({})
        client = next(f["contents"] for f in files if f["path"].endswith("_client.py"))
        # Absent entirely, rather than passed as an empty string that would override the default.
        assert "idempotency_header" not in client


class TestServerVariables:
    """A templated server URL (SPEC.md §3.4.0.2).

    graft passed the template through untouched once, so every request went to a host containing
    literal braces. The core now resolves the default; the target's job is to make each variable
    configurable without asking a caller to assemble a hostname.
    """

    TEMPLATED = [
        {
            "url": "https://us-east-1.api.example.com/v2",
            "urlTemplate": "https://{region}.api.example.com/{version}",
            "variables": [
                {
                    "wireName": "region",
                    "name": {"tokens": ["region"]},
                    "default": "us-east-1",
                    "enum": ["us-east-1", "eu-west-1"],
                    "description": "Data residency.",
                },
                {"wireName": "version", "name": {"tokens": ["version"]}, "default": "v2"},
            ],
            "default": True,
            "docs": DOCS,
        }
    ]

    def _client(self, servers: list[dict[str, Any]] | None = None) -> str:
        files = PythonEmitter(ir_with(servers=servers), {"packageName": "acme"}, BRAND).emit({})
        return next(f["contents"] for f in files if f["path"].endswith("_client.py"))

    def test_variables_become_keyword_arguments_and_an_f_string(self) -> None:
        client = self._client(self.TEMPLATED)
        # An enum becomes a Literal: the spec listed the valid values, and widening them to `str`
        # would leave a caller guessing at a region name.
        assert "region: Literal['us-east-1', 'eu-west-1'] | None = None" in client
        assert "version: str | None = None" in client
        assert (
            "base_url=base_url or f\"https://{region or 'us-east-1'}"
            ".api.example.com/{version or 'v2'}\"" in client
        )

    def test_both_the_sync_and_async_client_get_them(self) -> None:
        # Two constructors are emitted from one code path, so a change that reaches only one of them
        # is a silent asymmetry a caller discovers at runtime.
        assert self._client(self.TEMPLATED).count("region: Literal[") == 2

    def test_an_untemplated_server_stays_a_plain_literal(self) -> None:
        client = self._client()
        assert "base_url=base_url or 'https://api.acme.com'" in client
        # No variable, so no parameter for one. Matched on the parameter form rather than the bare
        # word: `# region client` is a preserve marker and appears in every generated client.
        assert "region:" not in client
